In [11]:
import os
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import math

In [7]:
os.listdir("../../Simstrat-Operational/Simulation/Soppensee/Results")

['V_out.dat',
 'U_out.dat',
 'T_out.dat',
 'S_out.dat',
 'num_out.dat',
 'nuh_out.dat',
 'NN_out.dat',
 'k_out.dat',
 'eps_out.dat',
 'P_out.dat',
 'B_out.dat',
 'Ps_out.dat',
 'HA_out.dat',
 'HW_out.dat',
 'HK_out.dat',
 'HV_out.dat',
 'Rad0_out.dat',
 'TotalIceH_out.dat',
 'BlackIceH_out.dat',
 'WhiteIceH_out.dat',
 'SnowH_out.dat',
 'WaterH_out.dat',
 'Qvert_out.dat',
 'simulation-snapshot.dat']

In [26]:
df = pd.read_csv("../../Simstrat-Operational/Simulation/Soppensee/Results/V_out.dat")
df["time"] = df.iloc[:,0].apply(lambda x: simstrat_time_to_datetime(x, reference_date))
df = df.set_index('time', drop=True)
df = df.drop(df.columns[0], axis=1)


In [27]:
df

-27.000       -26.000       -25.000  \
time                                                                
2010-09-22 10:00:02.880  0.000000e+00  0.000000e+00  0.000000e+00   
2010-09-22 16:00:02.880 -8.642400e-84 -5.270900e-81 -1.194200e-77   
2010-09-22 22:00:02.880  1.082800e-80  5.556400e-78  9.694500e-75   
2010-09-23 04:00:02.880 -1.671100e-78 -7.645700e-76 -1.298500e-72   
2010-09-23 10:00:02.880 -2.980900e-75 -1.444200e-72 -2.507600e-69   
...                               ...           ...           ...   
2021-01-02 22:00:02.880 -4.950800e-02 -5.969800e-02 -6.653700e-02   
2021-01-03 04:00:02.880  2.080900e-02  2.509200e-02  2.796800e-02   
2021-01-03 10:00:02.880  2.158500e-02  2.602700e-02  2.900800e-02   
2021-01-03 16:00:02.880 -4.987000e-02 -6.013500e-02 -6.702300e-02   
2021-01-03 22:00:02.880  4.546200e-02  5.482000e-02  6.110000e-02   

                              -24.000       -23.000       -22.000  \
time                                                                
2010-09-22 10:00:02.880  0.000000e+00  0.000000e+00  0.000000e+00   
2010-09-22 16:00:02.880 -2.890100e-74 -7.298300e-71 -1.672600e-67   
2010-09-22 22:00:02.880  1.764700e-71  3.583400e-68  7.581000e-65   
2010-09-23 04:00:02.880 -2.513100e-69 -5.706400e-66 -1.334100e-62   
2010-09-23 10:00:02.880 -4.594100e-66 -8.968500e-63 -1.645000e-59   
...                               ...           ...           ...   
2021-01-02 22:00:02.880 -7.059100e-02 -7.331700e-02 -7.548700e-02   
2021-01-03 04:00:02.880  2.967200e-02  3.082000e-02  3.173400e-02   
2021-01-03 10:00:02.880  3.077400e-02  3.196100e-02  3.290300e-02   
2021-01-03 16:00:02.880 -7.110500e-02 -7.384900e-02 -7.603100e-02   
2021-01-03 22:00:02.880  6.482200e-02  6.732500e-02  6.931500e-02   

                              -21.000       -20.000       -19.000  \
time                                                                
2010-09-22 10:00:02.880  0.000000e+00  0.000000e+00  0.000000e+00   
2010-09-22 16:00:02.880 -3.541900e-64 -7.357500e-61 -1.522700e-57   
2010-09-22 22:00:02.880  1.709200e-61  4.125300e-58  1.019900e-54   
2010-09-23 04:00:02.880 -3.075700e-59 -6.673700e-56 -1.278700e-52   
2010-09-23 10:00:02.880 -2.768700e-56 -4.179700e-53 -5.428800e-50   
...                               ...           ...           ...   
2021-01-02 22:00:02.880 -7.735400e-02 -7.907600e-02 -8.072100e-02   
2021-01-03 04:00:02.880  3.252100e-02  3.324800e-02  3.394300e-02   
2021-01-03 10:00:02.880  3.371200e-02  3.445600e-02  3.516300e-02   
2021-01-03 16:00:02.880 -7.790500e-02 -7.962800e-02 -8.127000e-02   
2021-01-03 22:00:02.880  7.102400e-02  7.259700e-02  7.409500e-02   

                              -18.000  ...        -9.000        -8.000  \
time                                   ...                               
2010-09-22 10:00:02.880  0.000000e+00  ...  0.000000e+00  0.000000e+00   
2010-09-22 16:00:02.880 -3.297400e-54  ... -3.905800e-25 -2.556800e-22   
2010-09-22 22:00:02.880  2.548300e-51  ...  8.414800e-24  5.164900e-21   
2010-09-23 04:00:02.880 -2.172200e-49  ... -3.626900e-23 -1.378300e-20   
2010-09-23 10:00:02.880 -6.210000e-47  ... -4.422600e-21 -3.042100e-18   
...                               ...  ...           ...           ...   
2021-01-02 22:00:02.880 -8.224600e-02  ... -9.642800e-02 -9.843600e-02   
2021-01-03 04:00:02.880  3.458900e-02  ...  4.063500e-02  4.150000e-02   
2021-01-03 10:00:02.880  3.581600e-02  ...  4.154900e-02  4.231100e-02   
2021-01-03 16:00:02.880 -8.278700e-02  ... -9.621500e-02 -9.801600e-02   
2021-01-03 22:00:02.880  7.547800e-02  ...  8.768400e-02  8.930300e-02   

                               -7.000        -6.000        -5.000  \
time                                                                
2010-09-22 10:00:02.880  0.000000e+00  0.000000e+00  0.000000e+00   
2010-09-22 16:00:02.880 -1.609200e-19 -9.646700e-17 -5.628000e-14   
2010-09-22 22:00:02.880  3.131800e-18  2.050700e-15  1.529800e-12   
2010-09-23 04:00:02.880 -3.5

In [38]:
depths

array([-27., -26., -25., -24., -23., -22., -21., -20., -19., -18., -17.,
       -16., -15., -14., -13., -12., -11., -10.,  -9.,  -8.,  -7.,  -6.,
        -5.,  -4.,  -3.,  -2.,  -1.,  -0.])

In [39]:
times

array([10856.4167, 10856.6667, 10856.9167, ..., 14612.4167, 14612.6667,
       14612.9167])

In [41]:
data

array([[ 0.0000e+00, -8.6424e-84,  1.0828e-80, ...,  2.1585e-02,
        -4.9870e-02,  4.5462e-02],
       [ 0.0000e+00, -5.2709e-81,  5.5564e-78, ...,  2.6027e-02,
        -6.0135e-02,  5.4820e-02],
       [ 0.0000e+00, -1.1942e-77,  9.6945e-75, ...,  2.9008e-02,
        -6.7023e-02,  6.1100e-02],
       ...,
       [ 0.0000e+00, -4.4719e-05,  1.7585e-04, ...,  5.4961e-02,
        -1.1067e-01,  9.3662e-02],
       [ 0.0000e+00, -9.6777e-04,  9.5287e-03, ...,  5.9921e-02,
        -1.0851e-01,  8.6101e-02],
       [ 0.0000e+00,  4.9702e-03,  1.4574e-02, ...,  6.2866e-02,
        -1.0815e-01,  8.2900e-02]])

In [20]:
def simstrat_time_to_datetime(days, reference_date):
    return reference_date + timedelta(days=days)

In [21]:
reference_date = datetime(1981, 1, 1)

In [7]:
times

array([10856.4167, 10856.6667, 10856.9167, ..., 14612.4167, 14612.6667,
       14612.9167])

In [18]:
times2 = np.array([simstrat_time_to_datetime(time, reference_date) for time in times])

In [19]:
list(times2)

[datetime.datetime(2010, 9, 22, 10, 0, 2, 880000),
 datetime.datetime(2010, 9, 22, 16, 0, 2, 880000),
 datetime.datetime(2010, 9, 22, 22, 0, 2, 880000),
 datetime.datetime(2010, 9, 23, 4, 0, 2, 880000),
 datetime.datetime(2010, 9, 23, 10, 0, 2, 880000),
 datetime.datetime(2010, 9, 23, 16, 0, 2, 880000),
 datetime.datetime(2010, 9, 23, 22, 0, 2, 880000),
 datetime.datetime(2010, 9, 24, 4, 0, 2, 880000),
 datetime.datetime(2010, 9, 24, 10, 0, 2, 880000),
 datetime.datetime(2010, 9, 24, 16, 0, 2, 880000),
 datetime.datetime(2010, 9, 24, 22, 0, 2, 880000),
 datetime.datetime(2010, 9, 25, 4, 0, 2, 880000),
 datetime.datetime(2010, 9, 25, 10, 0, 2, 880000),
 datetime.datetime(2010, 9, 25, 16, 0, 2, 880000),
 datetime.datetime(2010, 9, 25, 22, 0, 2, 880000),
 datetime.datetime(2010, 9, 26, 4, 0, 2, 880000),
 datetime.datetime(2010, 9, 26, 10, 0, 2, 880000),
 datetime.datetime(2010, 9, 26, 16, 0, 2, 880000),
 datetime.datetime(2010, 9, 26, 22, 0, 2, 880000),
 datetime.datetime(2010, 9, 27, 4, 